### ISSUE TITLE
Add a way to specify the db file

### ISSUE THREAD

**Issue by vdemeester** [google/licenseclassifier#20] opened 2020-04-22 14:17 UTC
In the case where I distribute the `binary` and the `db` file separately, I want to be able to specify where `licenseclassifier` should look for the db. This is related to `go-licences` (https://github.com/google/go-licenses/blob/master/licenses/classifier.go)

As of today, you need the source of the `go-license` binary in the right path (`GOPATH`, …) to be able to use it. 

Another alternative would be to embedded the `.db` in the binary :angel:

**Comment by jls5177** [comment] 2020-07-26 21:18
Hi @vdemeester, 

I ran into this exact issue when trying to pull in `go-licenses` to a work project. I found out that this package already contains a way to adjust the Archive location using the `OptionFn` slice within the `New()` function call. https://github.com/google/licenseclassifier/blob/master/classifier.go#L89:L94

The issue is the `go-licenses` does not expose a way to call this from the command line. I opened a pull request (https://github.com/google/go-licenses/pull/36) to fix that issue. If you are directly including the `licenseclassifier` module then you can do something similar to what I did in the PR.

Hope it helps.

**Comment by wcn3** [comment] 2020-09-17 15:22
Since this is an issue with the utility calling the classifier and not this code itself, closing the issue.

**Closed by wcn3** 2020-09-17 15:22 UTC
